### ISSUE TITLE
Environment variable expansion not working in password config

### ISSUE THREAD

**Issue by fireatwill** [octodns/octodns-mythicbeasts#31]
I created a provider and configured it according to the documentation, as follows:
```
providers:
  mythicbeasts:
    class: octodns_mythicbeasts.MythicBeastsProvider
    passwords:
      my.domain.: env/MYTHICBEASTS_PASSWORD
```

When running `MYTHICBEASTS_PASSWORD=xxx octodns-sync`, an unauthorized error was thrown:
```
Mythic Beasts unauthorized for zone: my.domain
```

I checked that my Mythic Beasts DNS API password was correct for the zone, using curl according to the Mythic Beasts documentation - it was.

Running `octodns-sync` with `--debug`, I could see that `env/MYTHICBEASTS_PASSWORD` was being passed to the API verbatim - i.e. it had not been expanded into the environment variable.

Reading through the octodns code, it looked like the `env/` expansion only happens for "top-level" provider config values, i.e.:
```
providers:
  mythicbeasts:
    class: octodns_mythicbeasts.MythicBeastsProvider
    password: env/THIS_PASSWORD_WOULD_EXPAND_CORRECTLY
    passwords:
      my.domain.: env/THIS_PASSWORD_DOES_NOT_EXPAND
```

At this stage it is perhaps worth saying that I'm not entirely sure where a fix to this issue should be applied - in octodns itself, or in the octodns-mythicbeasts provider.

Regardless, I wanted to make this work, and I didn't want to store the password in my config file, so I hacked up a fix. I'm not a Python programmer, and I couldn't see an obvious way to patch octodns itself to iterate nested values, so doing it inside octodns-mythicbeasts seemed easier. Please see attached patch.
[octodns-mythicbeasts.patch](https://github.com/octodns/octodns-mythicbeasts/files/13559605/octodns-mythicbeasts.patch)

Based on my limited testing, this works, but as I say above it may not be the "correct" place to fix this issue.
